sed-builder/src/test/java/cfa/vo/sed/science/stacker/SedStackerStackerTest.java

The main fixes were done in jbudynk/sedstacker#14.
Here, the y-error control arrays in SedStackerStackerTest are updated to match
the jbudynk/sedstacker fix.

Helps fix #73. SEDStacker y-errors incorrectly matched after redshifting

---

sed-builder/src/test/java/cfa/vo/sed/science/stacker/SedStackerStackerTest.java

The main fixes were done in jbudynk/sedstacker#14.
Here, the y-error control arrays in SedStackerStackerTest are updated to match
the jbudynk/sedstacker fix.

Helps fix #73 (SEDStacker y-errors incorrectly matched after redshifting)

---

sed-builder/src/main/java/cfa/vo/sed/science/stacker/NormalizationConfiguration.java
sed-builder/src/main/java/cfa/vo/sed/science/stacker/SedStackerFrame.form
sed-builder/src/main/java/cfa/vo/sed/science/stacker/SedStackerFrame.java

fix #115 
Needs some cleaning up in the code though. There's possibly some
unnecessary code...

Fix #115 (SED Stacker GUI norm params not binding correctly.)

---

.travis.yml

[release-note]
N/A
[release-note]
[story] #140 [/story]
This PR introduces a basic Travis CI configuration for Iris.
The `maven` repository as well as the `miniconda` installation are cached for efficiency.
xfvb is configured although it should not really be used at this point.
The following Travis CI build shows that Travis builds are active and the Iris tests pass:
https://travis-ci.org/ChandraCXC/iris/builds/86906266

140 setup travis ci

---

.travis.yml
README.md
iris/src/test/java/cfa/vo/gui/BuilderMainViewIT.java
pom.xml

[release-note]
N/A
[/release-note]
Resolve #141.
This PR introduces separate configurations for the unit (`test` phase) and integration (`verify` phase) tests. Coverage analysis plugins are also configured so that coverage information can be created and used for reports. In particular, coverage information is sent to the coveralls service after a successful Travis CI builds.
https://coveralls.io/builds/3975496
The aggregation of the coverage information is performed by coveralls in the `jacoco` profile, and by Sonar in the `sonar` profile, with some configuration tweaks in the `pom` itself.
I also updated the README with information on how to run the different test suites and the coverage analysis plugins.
The following Travis Build:
https://travis-ci.org/ChandraCXC/iris/jobs/87897375 …

141 setup coverage analysis jacoco

---

iris-common/src/main/java/cfa/vo/iris/AbstractIrisApplication.java
iris-common/src/test/java/cfa/vo/iris/common/SedMessageTest.java
iris-common/src/test/java/cfa/vo/iris/common/SedTest.java
iris/src/test/resources/log.properties
pom.xml
samp-factory/src/test/java/cfa/vo/interop/SAMPFactoryTest.java
sed-builder/src/main/java/cfa/vo/sed/builder/AsciiConf.java
sed-builder/src/main/java/cfa/vo/sed/science/stacker/StackTableModel.java
sed-builder/src/test/java/cfa/vo/sed/builder/NEDImporterTest.java
sed-builder/src/test/java/cfa/vo/sed/builder/SegmentImporterTest.java
sed-builder/src/test/java/cfa/vo/sed/filters/ConfigurationManagerTest.java
sed-builder/src/test/java/cfa/vo/sed/filters/FileFormatsTest.java
sed-builder/src/test/java/cfa/vo/sed/filters/PhotometryCatalogTest.java
sed-builder/src/test/java/cfa/vo/sed/filters/PhotometryPointCloneTest.java
sed-builder/src/test/java/cfa/vo/sed/science/interpolation/SherpaRedshifterTest.java
sed-builder/src/test/java/cfa/vo/sed/science/stacker/SedStackTest.java
sed-builder/src/test/java/cfa/vo/sed/science/stacker/SedStackerNormalizerTest.java
sed-builder/src/test/java/cfa/vo/sed/science/stacker/SedStackerRedshifterTest.java
sed-builder/src/test/java/cfa/vo/sed/science/stacker/SedStackerStackerTest.java
test-components/src/main/java/cfa/vo/iris/test/TestBuilder.java
test-components/src/main/java/cfa/vo/iris/test/TestLogger.java
test-components/src/main/java/cfa/vo/iris/test/r/RComponent.java

Building off Omar's change.
Logs for units tests are dumped into surefire output.
Removed most of the prints to std out - those that are left are only in the CLI and visible for Consumers' sake.
Formatted logfiles for readability, no longer split across lines, e.g.:
2015-11-06 11:48:32 cfa.vo.iris.ComponentLoader initComponents [INFO] Loading class: cfa.vo.iris.ComponentLoaderTest$BrokenTestIrisComponent
2015-11-06 11:48:32 cfa.vo.iris.ComponentLoader initComponents [SEVERE] Could not construct component cfa.vo.iris.ComponentLoaderTest$BrokenTestIrisComponent
java.lang.RuntimeException: I don't work
at cfa.vo.iris.ComponentLoaderTest$BrokenTestIrisComponent.(ComponentLoaderTest.java:73)
Ultimately I think we should setup an option for specifying log files for the Iris application VIA the …

Logging for Unit Tests Cleanup

---

.gitmodules
iris-common/pom.xml
iris-common/src/site/markdown/index.md
iris-common/src/site/site.xml
iris-specview/src/site/markdown/index.md
iris-specview/src/site/site.xml
iris-visualizer/pom.xml
iris/pom.xml
iris/src/site/markdown/index.md
iris/src/site/site.xml
pom.xml
samp-factory/pom.xml
samp-factory/src/site/markdown/index.md
samp-factory/src/site/site.xml
sed-builder/pom.xml
sed-builder/src/site/markdown/index.md
sed-builder/src/site/site.xml
test-components/pom.xml
test-components/src/site/markdown/index.md
test-components/src/site/site.xml

Address #144, #150
This PR:
- migrates the current Iris v2.1 user documentation from the home-grown CXC site building system to Maven site.
- adds very simple sites for each project module so that developers can view the dependencies and other build information. E.g., `sed-builder/src/site/`.
- adds a new repository, [iris-docs](https://github.com/jbudynk/iris-docs), as a submodule to the Iris project. This contains all the Iris user documentation and images (#144).
- the site can now be pushed to versioned sites on the CXC server using `mvn site:deploy` (#150). This requires the CXC server to be added to the developer's `settings.xml` file. The site directory name is ${project.version}.
The site build still needs the following additions before completion:
- create profiles to push the …

Docs migration

---

iris-common/src/site/site.xml
iris-specview/src/site/site.xml
iris-visualizer/pom.xml
iris-visualizer/src/site/markdown/index.md
iris-visualizer/src/site/site.xml
iris/src/site/site.xml
pom.xml
samp-factory/src/site/site.xml
sed-builder/src/site/site.xml
test-components/src/site/site.xml

This PR is in response to PR #182. Not all the necessary changes were added to the docs migration in PR #182, so I've added the following updates to fix this:
- I put spaces between the email parts, like "jbudynkiewicz @ cfa.harvard.edu". Please let me know if you'd prefer me to just get rid of them, or if we should just provide irisdev as the email, or anything else. Also, I removed Janet's email because I figure she wouldn't want people emailing her about Iris (and we'd want to get the emails first anyhow) - let me know if I should add it back in.
- I introduced the <distributionManagement> section back into the main POM so that site:stage works. By default, the website built with site:stage is stored in `target/staging`, despite the fact that the <url> element says to store it at the …

Fix docs migration

---

iris-common/src/main/java/cfa/vo/iris/ComponentLoader.java
iris-common/src/test/java/cfa/vo/iris/ComponentLoaderTest.java
iris/src/main/java/cfa/vo/iris/Iris.java

We were just missing a call to get the extra components from the Command Line.
Here's a potential fix.

Add CLI components to componentLoader. Closes #232.

---

iris-common/src/main/java/cfa/vo/iris/sed/ExtSed.java
iris-common/src/test/java/cfa/vo/iris/test/unit/AbstractGUITest.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/VisualizerComponent.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/StilPlotter.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/VisualizerComponentTest.java

Resolve #224 
This PR subscribes the plotter to sed events. All sed events trigger a reset of the plotter view. This may or may not be the desired eventual behavior, depending also on the work in #225.
For instance, the `reset` logic does not discriminate between resetting the viewport after a click of the "reset" button or plotting a new SED once it has been selected. Also, one may want to attach the viewport features as SED attachments and then restore the customized viewport once an SED regains focus, so that user's customization are preserved, at least during a session.
So, we may want to split `reset` into two methods with different scopes. This seems out of the scope of this PR, but we may decide otherwise.
There are many more unit tests that this PR may add, but it is hard to …

subscribe plotter to events, unit tests

---

.gitmodules
iris-common/src/main/java/cfa/vo/iris/sed/ExtSed.java
iris-common/src/test/java/cfa/vo/iris/test/unit/AbstractGUITest.java
iris-visualizer/pom.xml
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/VisualizerComponent.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/StilPlotter.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/VisualizerComponentTest.java
pom.xml
sed-builder/src/main/java/cfa/vo/sed/gui/LoadSegmentFrame.java
sed-builder/src/main/java/cfa/vo/sed/gui/SampChooser.java

Resolve #239.
This PR introduces a simple benchmark assessing SEDs can be loaded and displayed in a reasonable amount of time.
This PR relies on a new git repository for the test data, so to reduce the footprint of the main repository.
The benchmark relies on a simple annotation from JUnit which will fail the test if it takes longer than a timeout. The timeout keeps into account the test setup time, so some heuristics were used to determine a reasonable timeout of 2500 milliseconds. Interactive testing was performed to ensure that the system is responsive.
We can use something fancier or try to roll our own benchmark logic if required.
I also had to remove some code that was added to warn the users when too large files were loaded. 
Plus, since SEDLib does not handle URLs directly, I …

Iris 239 plotter performance test

---

iris-common/src/main/java/cfa/vo/iris/desktop/IrisDesktop.java
iris-common/src/test/java/cfa/vo/iris/test/unit/ApplicationStub.java
iris-common/src/test/java/cfa/vo/iris/test/unit/IMainWindow.java
iris-common/src/test/java/cfa/vo/iris/test/unit/MainWindow.java
iris-common/src/test/java/cfa/vo/iris/test/unit/StubAdapter.java
iris-common/src/test/java/cfa/vo/iris/test/unit/StubWorkspace.java
iris/src/test/java/cfa/vo/gui/SAMPConnectionTest.java
iris/src/test/java/cfa/vo/iris/desktop/IrisDesktopSampConnectionTest.java
samp-factory/src/main/java/cfa/vo/interop/SampService.java

Resolve #233
Resolve #209  
This PR fixes an issue in #231 by which the Sherpa icon does not update when Sherpa is not connected.
There are unit tests exercising the relevant code in the IrisDesktop class, but integration tests are hard to implement as sherpa-samp is an external process, and we should reliably be able to shut it down and start it up again from Java, and we currently can't do it.
This PR relies on a change in sherpa-samp, namely the introduction of a `sherpa.ping` mtype handler.

fix sherpa connection icon and add unit tests

---

iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/ColorPalette.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/HSVColorPalette.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/SedPreferences.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/preferences/SedPreferencesTest.java

Addresses ChandraCXC/iris-dev#14
This PR introduces a very simple automatic coloring for added Segments. Using an HSV cylinder as the color space, the golden ratio is used to create a set of fairly distinct colors. I say "fairly" because only the hue changes, not the brightness or saturation. The colors have full brightness and saturation. In commit e2c6522, I tried to change the brightness and saturation every six colors or so to try to get more variety. However, this algorithm produced a lot of pale yellow colors, which is not wanted.
I created a ColorPalette interface to use for other color palettes we may create later.
Issue ChandraCXC/iris#258 causes problems for Segment coloration. If two or more segments have the same Target Name, the SegmentLayer colors are replaced with the …

Iris dev 14 implement automatic color selection

---

iris-visualizer/src/main/java/cfa/vo/iris/visualizer/metadata/MetadataBrowserView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/SegmentLayer.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/SedPreferences.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/VisualizerCommand.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/VisualizerComponentPreferences.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/StilPlotter.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/metadata/MetadataBrowserViewTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/preferences/SedPreferencesTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/preferences/VisualizerComponentPreferencesTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/stil/StilPlotterTest.java

Closes https://github.com/ChandraCXC/iris-dev/issues/7
Adds a segment event listener to the VisualizerComponentPrefereces settings to give the plotter/metadata browser more detailed information into sedmanager changes, allowing more efficient updates of the model and GUI. This change drastically improves performance in the plotter - at least while testing on my box and on my laptop.
This overlaps slightly with https://github.com/ChandraCXC/iris/pull/262, and this should probably be incorporated in some manner so that changing plot preferences doesn't reset the existing plot bounds.
Important note - we have access to the plotter bounds though the plane aspect object in the PlotDisplay.

Split Reset Method #7

---

iris-common/src/main/java/cfa/vo/iris/sed/stil/SegmentStarTable.java
iris-common/src/main/java/cfa/vo/iris/sed/stil/SerializingStarTableAdapter.java
iris-common/src/main/java/cfa/vo/iris/utils/UTYPE.java
iris-common/src/test/java/cfa/vo/iris/sed/stil/SegmentStarTableTest.java
iris-common/src/test/java/cfa/vo/iris/sed/stil/SerializingStarTableTest.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/metadata/IrisMetadataTableModel.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/metadata/MetadataBrowserMainView.form
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/metadata/MetadataBrowserMainView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/SegmentLayer.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/SedPreferences.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/VisualizerComponentPreferences.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/IrisStarJTable.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/tables/ColumnInfoMatcher.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/tables/ColumnMappingStarTable.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/tables/ColumnMatcher.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/tables/ColumnMetadataStarTable.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/tables/IrisStarTable.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/tables/IrisStarTableAdapter.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/tables/StackedStarTable.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/tables/UtypeColumnInfoMatcher.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/tables/UtypeColumnMatcher.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/metadata/MetadataBrowserMainViewTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/preferences/SedPreferencesTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/stil/tables/ColumnMappingStarTableTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/stil/tables/ColumnMetadataStarTableTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/stil/tables/IrisStarTableAdapterTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/stil/tables/StackedStarTableTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/stil/tables/VisualizerStarTableTest.java

This PR closes
https://github.com/ChandraCXC/iris-dev/issues/19
https://github.com/ChandraCXC/iris-dev/issues/20
And additional deals with making the metadata browser/visualizer component more stable in general.
We include a new class, StackedStarTable, which is essentially a http://www.star.bristol.ac.uk/~mbt/stil/javadocs/uk/ac/starlink/table/ConcatStarTable.html that also maps all the columns in the provided list of startables into a single metadata star table. Users provide a column matcher class which determines whether or not two columns should "line up". In our case we have implemented a single class, the UtypeColumnInfoMatcher, which may or may not need to be improved upon in the future. For now it appears to line data up well in the test cases that I have provided.
This is …

iris-dev#19 Viewing Multiple Segments in the Metadata Browser

---

iris-common/src/main/java/cfa/vo/iris/sed/stil/SegmentStarTable.java
iris-common/src/test/java/cfa/vo/iris/sed/stil/SegmentStarTableTest.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/IrisStarJTable.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/stil/IrisStarJTableTest.java

Closes https://github.com/ChandraCXC/iris-dev/issues/53
Added a custom JTableHeader to the IrisStarJTable class to support showing tooltips that look something like:
name: DataFluxStatErr
unit: Jy
utype: some.utype
Also fixed an issue with the units strings not being set on SegmentStarTable creation and updated the test to cover that case.
Supports permuting and resizing columns.

iris-dev#53 Show Column Metadata in Tooltip

---

iris-visualizer/src/main/java/cfa/vo/iris/visualizer/metadata/MetadataBrowserMainView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/MouseCoordinateMotionListener.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/MouseListenerManager.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotPointSelectionDetailsListener.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotPointSelectionListener.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.form
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/StilPlotterMouseListener.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/StilPlotterPointSelectionListener.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/VisualizerComponentPreferences.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/IrisStarJTable.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/StilPlotter.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/tables/IrisStarTable.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/metadata/MetadataBrowserMainViewTest.java

Small PR which will setup later tasks for other mouse listeners.
For now, this closes: https://github.com/ChandraCXC/iris-dev/issues/15, and will display the mouse's coordinates in the stil plotter in the two places we reserved for them in the plot view.
I figure for now we can put mouse listener classes into the MouseListenerManager class, which the StilPlotter can maintain a pointer to to make sure each new mouse listener is added to the PlotDisplay whenever one is created. I left it in the preferences class so that other callers have access if necessary.
There's also a simple, silly Point Selection Listener in place just to show how it works. Whomever picks up the point selection event tasks can use it as a template for what point selection events look like.
[EDIT]
This now also closes …

iris-dev#15 Several Mouse Function for the Plotter

---

iris-common/src/main/java/cfa/vo/iris/fitting/ConfResultsConverter.java
iris-common/src/main/java/cfa/vo/iris/fitting/FitConfiguration.java
iris-common/src/test/java/cfa/vo/iris/test/unit/TestUtils.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/ConfidencePanel.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FitController.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FittingMainView.form
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FittingMainView.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/ModelsTreeModel.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/FittingToolComponent.java
iris-visualizer/src/test/java/cfa/vo/iris/fitting/FitControllerTest.java
iris-visualizer/src/test/java/cfa/vo/iris/fitting/FittingMainViewTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/FittingToolComponentTest.java
iris-visualizer/src/test/resources/cfa/vo/iris/fitting/fit.output
iris-visualizer/src/test/resources/cfa/vo/iris/visualizer/fit.output
iris/src/test/java/cfa/vo/iris/fitting/FittingFunctionalIT.java
iris/src/test/resources/cfa/vo/iris/fitting/fit.output
samp-factory/src/main/java/cfa/vo/sherpa/models/DefaultModel.java

I will issue smaller PRs against the iris-dev-45 branch. That can't be a PR just yet because it doesn't have a diff with sprint-9.
This PR addresses part of chandracxc/iris-dev#45 by allowing users to save fit results in human readable text files. In particular, it fulfills req 2.2.b.1.
The only, small improvement I would like to make (pending review) is to add a timestamp when the file is saved, although we should really have a timestamp for fits.
This implementation has several improvements over the Iris 2.1 code. It includes data about the user models, as well as information regarding the optimizer and the cost function, which were missing in the old implementation.
Also, after an iteration with @jbudynk we decided to include all models in the output, without making a distinction …

Save fit summary in human format

---

iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.form
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/StilPlotter.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/stil/StilPlotterTest.java

This PR addresses the zoom in/out buttons previously disabled in PR #270. The zooming algorithm uses STILTS's [Axis::zoom() method](https://github.com/Starlink/starjava/blob/master/ttools/src/main/uk/ac/starlink/ttools/plot2/Axis.java#L486) to calculate the min and max range values. The tricky part of the algorithm is determining the central value of an axis, which depends on the axis spacing (log or linear).
Tests are in StillPlotterTest which test that zooming in once and zooming back out brings you back to the same view.

Add zoom button functionality

---

iris-common/src/main/java/cfa/vo/iris/sed/stil/SegmentStarTable.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/masks/RowSubsetMask.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/metadata/MetadataBrowserMainView.form
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/metadata/MetadataBrowserMainView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/metadata/SegmentExtractor.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotPointSelectionListener.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/SedModel.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/VisualizerComponentPreferences.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/IrisStarJTable.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/StilPlotter.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/tables/IrisStarTable.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/tables/IrisStarTableAdapter.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/metadata/MetadataBrowserMainViewTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/metadata/SegmentExtractorTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/preferences/SedPreferencesTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/stil/IrisStarJTableTest.java
iris/src/main/java/cfa/vo/iris/ConsistencyChecker.java

Supersedes https://github.com/ChandraCXC/iris/pull/283 and https://github.com/ChandraCXC/iris/pull/279
Closes
https://github.com/ChandraCXC/iris-dev/issues/58
https://github.com/ChandraCXC/iris-dev/issues/52
https://github.com/ChandraCXC/iris-dev/issues/51
Changes to support sorting on column values in the metadata browser, as well as extracting the current selection in the metadata browser to a new SED.
Builds on the RowSelection model in the IrisStarJTable class to give outside callers clean access to the underlying StarTables and rows, without having to deal with row sorting or ordering of the tables. The plotter data table in the metadata browser is sorted by spectral value by default. Order and selection is currently reset with the metadata browser, so applying masks will reset to …

iris-dev#51,52,58 Sorting and Extraction in the Metadata Browser

---

iris-common/src/main/java/cfa/vo/iris/fitting/ConfResultsConverter.java
iris-common/src/main/java/cfa/vo/sherpa/SherpaClient.java
iris-common/src/test/java/cfa/vo/iris/test/unit/TestUtils.java
iris-visualizer/pom.xml
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FitController.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/ModelsTreeModel.java
iris-visualizer/src/test/java/cfa/vo/iris/fitting/FitControllerIT.java
iris-visualizer/src/test/java/cfa/vo/iris/fitting/FitControllerTest.java
iris-visualizer/src/test/java/cfa/vo/iris/fitting/FittingMainViewTest.java
iris/src/test/java/cfa/vo/iris/fitting/FittingFunctionalIT.java
samp-factory/src/main/java/cfa/vo/sherpa/Data.java
samp-factory/src/main/java/cfa/vo/sherpa/models/ParameterImpl.java
samp-factory/src/main/java/cfa/vo/sherpa/optimization/MethodDeserializer.java
samp-factory/src/main/java/cfa/vo/sherpa/stats/StatDeserializer.java
sed-builder/src/main/java/cfa/vo/sed/science/integration/SherpaIntegrator.java

Resolve chandracxc/iris#73.
This PR introduces model evaluation features to the `FitController` class.
I made some clean up in the relative `sherpa-samp` call, which then required a good simplification in the `SherpaIntegrator` class.
I am building on top of #292 because of some infrastructure requirements. The only commit relevant to this PR is e268e39.

Fitting Tool Evaluate Model

---

iris-visualizer/src/main/java/cfa/vo/iris/visualizer/metadata/MetadataBrowserMainView.form
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/metadata/MetadataBrowserMainView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/IrisStarJTable.java

Resolves https://github.com/ChandraCXC/iris-dev/issues/100
This is unrelated to https://github.com/ChandraCXC/iris-dev/issues/101.
Basically just had a stray empty string in the tooltip setting for one of the metadata browser panels. Also added a check to make sure we don't ask for the -1 indexed column in the startable - which can happen if the header doesn't fill the entire frame.

iris-dev#100 Fix Tooltip in Metadata Browser

---

iris-common/src/main/java/cfa/vo/iris/sed/stil/SegmentColumn.java
iris-common/src/main/java/cfa/vo/iris/sed/stil/SegmentStarTable.java
iris-common/src/main/java/cfa/vo/iris/units/spv/YUnits.java
iris-common/src/test/java/cfa/vo/iris/sed/stil/SegmentStarTableTest.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/SegmentModel.java

Addresses ChandraCXC/iris-dev#72
This PR fixes an issue where conversions between magnitudes and flux/flux densities were not done correctly.
First, the wrong units conversion method was being used in [`SegmentStarTable::setFluxUnits()`](https://github.com/ChandraCXC/iris/blob/master/iris-common/src/main/java/cfa/vo/iris/sed/stil/SegmentStarTable.java#L221). Before, it was using `UnitsManager::convertY()`. Now, it uses `UnitsManager::convertErrors()` for the flux errors which has a special cases for converting errors to/from magnitude units (in the Specview units code).
Next, Specview's `YUnits` conversion method for AB magnitudes wasn't perfect. This has been fixed in line [862](https://github.com/ChandraCXC/iris/blob/iris-dev-72-magnitudes-conversion/iris-common/src/main/java/cfa/vo/iris …

Fix issue with AB magnitudes not being converted correctly.

---

iris-common/src/main/java/cfa/vo/iris/sed/ExtSed.java
iris-common/src/main/java/cfa/vo/iris/sed/stil/SegmentColumn.java
iris-common/src/main/java/cfa/vo/iris/sed/stil/SegmentStarTable.java
iris-common/src/main/java/cfa/vo/sherpa/SherpaClient.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FitController.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/SedModel.java
iris-visualizer/src/test/java/cfa/vo/iris/fitting/FitControllerIT.java
iris-visualizer/src/test/java/cfa/vo/iris/fitting/FitControllerTest.java

This PR modifies the model evaluation method created in #298 to return a `SegmentStarTable`, which can be integrated in the visualizer to plot model functions. It also accepts a `SedModel` instance as an argument, as this is the model class used by the visualizer internally.
Units conversion should be properly handled by the method and its dependencies. When reviewing, please pay special attention to the tests: they should make sure the conversion is properly handled, but we need careful validation that I did the right calculations (I used astropy to validate the conversions, but I might have made the same mistake twice ;).
Also, you are welcome to suggest error handling test cases to add.
Note that this PR is based off of #303 for convenience, but only 3db91cf is relevant for this PR.

Model evaluation startable

---

iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.form
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/StilPlotter.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/plotter/StilPlotterTest.java

The little arrows in the plot window didn't do anything - so I added a simple notion of panning to the StilPlotter.
Basically for linear scales the axis moves by 1/4 the size of the axis. So panning on an axis of length 10 will move the axis by 2.5 in the specified direction.
Log scales will pan by a factor of 1/3, in either the positive or negative direction. I tried to figure out what Iris2.1 does, but it's panning is rather odd, so hopefully that makes sense.
Easy to change later on, I just wanted this functionality to be there.

Enable Panning Buttons for the Plot Window

---

iris-common/src/main/java/cfa/vo/iris/sed/stil/SegmentColumn.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.form
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/StilPlotter.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/FunctionModel.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/LayerModel.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/SedModel.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/VisualizerDataModel.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/tables/SortedStarTable.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/plotter/StilPlotterTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/stil/tables/SortedStarTableTest.java

Adds the capability of plotting a model on top of an SED.
This PR provides a very simple visualization of a plotted model. It assumes that the evaluated model is a SegmentStarTable. The method is called with `StilPlotter::plot_model(SegmentStarTable model)`.
A `FunctionModel` is the evaluated model's (or function's) "model", which contains the STILTS preferences for plotting a StarTable as a line. It is similar to the `SegmentModel` object. It's list of preferences is shorter: you can control the line thickness, color, and pattern. For now, the defaults are the same as STILTS' defaults: a solid, red line of thickness 1 (thin like Iris 2.1's line).
To take a look at the model on the visualizer, I've added a dummy "Plot Model" functionality to the PlotterView frame. It plots a FunctionModel …

Plot fitted model

---

iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.form
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/StilPlotter.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/FunctionModel.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/LayerModel.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/SedModel.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/VisualizerDataModel.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/plotter/StilPlotterTest.java

Basic implementation of the secondary plotter - in appearance only! Need to have the FunctionModel infrastructure in place and then should be able to add layers to the Residuals plot display in the setupResidualMapEnvironment method.
I spent some time trying to figure out how to fix the planeaspects together so that they would zoom at the same time, but it's non-trivial so leaving it for a later time.
For now the residuals will just plot the same first layer that's available in the regular plotter - that will change going forward.
This is also based off of https://github.com/ChandraCXC/iris/pull/303, relevant first commit is  	c0d6005, then the last 4.

Add Residuals Plot to StilPlotter

---

iris-visualizer/src/main/java/cfa/vo/iris/fitting/FitController.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FittingMainView.form
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FittingMainView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/FittingToolComponent.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/IrisVisualizer.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/VisualizerComponent.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/HSVColorPalette.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotPreferences.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/StilPlotter.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/SedModel.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/VisualizerComponentPreferences.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/VisualizerDataModel.java
iris-visualizer/src/test/java/cfa/vo/iris/fitting/FitControllerIT.java
iris-visualizer/src/test/java/cfa/vo/iris/fitting/FitControllerTest.java
iris-visualizer/src/test/java/cfa/vo/iris/fitting/FittingMainViewTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/FittingToolComponentTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/metadata/MetadataBrowserMainViewTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/plotter/CoPlottingTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/plotter/StilPlotterTest.java

Resolves 
https://github.com/ChandraCXC/iris-dev/issues/76
https://github.com/ChandraCXC/iris-dev/issues/77
Adds basic support for plotting the evaluated models after a fit. After a fit is completed the fitting tool immediately calls to evaluate the sed asynchronously from the visualizer preferences. I added a singleton holder, IrisVisualizer, for objects that need to be shared between the fitting tool and the plotter/MB. At this point it's pretty simple, but will need to be expanded for future integration of the two components.
A few points:
+ The models are evaluated asynchronously, and the datamodel will be updated after the evaluation completes.
+ As of now there is no notion of validation on the models. That will come in a later commit.
+ I fixed the unit tests in the visualizer, …

iris-dev#77 Plot Evaluated Models

---

iris-common/src/main/java/cfa/vo/iris/fitting/FitConfiguration.java
iris-common/src/main/java/cfa/vo/iris/sed/stil/SegmentStarTable.java
iris-common/src/test/java/cfa/vo/iris/sed/stil/SegmentStarTableTest.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FitController.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/FittingToolComponent.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/IrisVisualizer.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.form
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/StilPlotter.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/UnitsManagerFrame.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/SedModel.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/VisualizerDataModel.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/VisualizerComponentTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/plotter/StilPlotterTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/preferences/SedPreferencesTest.java

Resolves
https://github.com/ChandraCXC/iris-dev/issues/111
Validation uses hashCodes built on the spectral, flux, and error values in a SegmentStarTable. The logic being that a fit will be valid as long as those values haven't changed. The SedModel uses those hashCodes to produce a "hashCode" for all the segments in the SED. Note that I call it a version rather than a HashCode, as I don't really want to overwrite the SedModel's hashCode function as it's pretty heavily utilized already in the Visualizer.
Right now the default behaviour is to show a warning message once when a function model is no longer valid for the given SedModel. Once the user has acknowledged the warning it will not be shown again until the SED version number changes.
The Version numbers are recorded in two places: The …

iris-dev#111 Model Validation

---

iris-common/src/main/java/cfa/vo/iris/fitting/FitConfiguration.java
iris-common/src/main/java/cfa/vo/iris/gui/widgets/ModelViewerPanel.form
iris-common/src/main/java/cfa/vo/iris/gui/widgets/ModelViewerPanel.java
iris-common/src/main/java/cfa/vo/sherpa/SherpaClient.java
iris-common/src/test/java/cfa/vo/iris/test/unit/TestUtils.java
iris-common/src/test/java/cfa/vo/sherpa/SherpaClientTest.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/ConfidencePanel.form
iris-visualizer/src/main/java/cfa/vo/iris/fitting/ConfidencePanel.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FitResultsPanel.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FittingMainView.form
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FittingMainView.java
iris-visualizer/src/test/java/cfa/vo/iris/fitting/ConfidencePanelTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/FittingToolComponentTest.java
iris-visualizer/src/test/resources/cfa/vo/iris/fitting/fit.json
iris-visualizer/src/test/resources/cfa/vo/iris/visualizer/fit.json
iris/src/test/java/cfa/vo/iris/fitting/FittingFunctionalIT.java
iris/src/test/resources/cfa/vo/iris/fitting/fit.output
samp-factory/src/main/java/cfa/vo/sherpa/Confidence.java
samp-factory/src/main/java/cfa/vo/sherpa/ConfidenceConfiguration.java
samp-factory/src/main/java/cfa/vo/sherpa/Configuration.java

This PR fixes three issues with the fitting tool:
* chandracxc/iris-dev#91 - the sigma label now updates when the confidence is calculated. A potential issue here is that the confidence calculation must be performed and succeed for sherpa-samp to return the percentage value corresponding to the user's input. An improvement would be to perform the calculation in java on the fly.
* chandracxc/iris-dev#99 - confidence now seems to properly work. Results are consistent with the ones in Iris 2.1. The problem in the previous code was that the SAMP configuration was not properly built, and unfortunately sherpa-samp does not much in terms of error handlind.
* chandracxc/iris-dev#92 - introduced gridbag layout in GUI to try and fix some OSX issues. Not all issues are resolved, but this is an …

Fix fitting tool bugs

---

iris-common/src/main/java/cfa/vo/iris/sed/stil/IrisDataStarTable.java
iris-common/src/main/java/cfa/vo/iris/sed/stil/SegmentStarTable.java
iris-common/src/main/java/cfa/vo/sherpa/SherpaClient.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FitController.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/SedModel.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/stil/tables/IrisStarTable.java
iris-visualizer/src/test/java/cfa/vo/iris/fitting/FitControllerIT.java
iris-visualizer/src/test/java/cfa/vo/iris/fitting/FitControllerTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/preferences/SedPreferencesTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/stil/tables/MaskingTest.java

Replaces #312 - opening against master.
Resolves
ChandraCXC/iris-dev#112
Added support for the fitting tool to get masked data instead of all the data when computing a fit. Additional unit/functional tests at several layers verify the changes.
One note, I made an interface for the star table that we use for plotting so that we can interchangeably use IrisStarTables and SegmentStarTables, when required.
Also, note that this is branched off model-validation for ease of viewing.
In order to satisfy the conditions of the FittingFunctionalIT, we always use the original Spectral, Flux, and Flux Error values when fitting, rather than the data currently in the plotter.
EDIT:
Also included the changes for optimizing construction of SegmentStarTables.

Fit masked data

---

iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/MouseXRangesClickedListener.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/StilPlotter.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/FittingRangeModel.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/LayerModel.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/VisualizerDataModel.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/plotter/StilPlotterTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/preferences/FittingModelTest.java

Opening against #311 since this includes all of those changes.
Plots fitting ranges as a new layer in the stil plotter. There's a significant TODO in the StilPlotter's construction of the plot display, in that we don't have access to the aspect's bounds prior to constructing a plot, so we just do it twice, if necessary. This keeps the fitting ranges from affecting the default view ranges on the plotter.
Ranges are always plotted at 10% from the y-axis minimum.

Plot Fitting Ranges

---

iris-common/src/main/java/cfa/vo/iris/sed/stil/SegmentStarTable.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FitController.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/plotter/StilPlotterTest.java

Fixes ChandraCXC/iris-dev#113 - bug in model plotting units conversion
The model units in the VisualizerDataModel weren't being updated with the rest of the data on the plotter. Now, the model values are converted to the plotter units along with the segment data in `SegmentStarTable.setFluxUnits()`.

Fix plotted model units conversion

---

iris-common/src/main/java/cfa/vo/iris/fitting/ConfResultsConverter.java
iris-common/src/main/java/cfa/vo/iris/fitting/FitConfiguration.java
iris-common/src/main/java/cfa/vo/sherpa/SherpaClient.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/ConfidencePanel.form
iris-visualizer/src/main/java/cfa/vo/iris/fitting/ConfidencePanel.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FitController.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FittingMainView.form
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FittingMainView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/SedModel.java
samp-factory/src/main/resources/cfa/vo/sherpa/models/sherpa_models.xml

Add the following features to Fitting Tool:
* `Fit` button is now disabled during a fit.
* `Compute` confidence button is now disabled during a calculation.
* `Stop` buttons for fitting and confidence limit calculations.
* Add a `Clear All` button for resetting fit and confidence.
Tests performed interactively. It turns out Iris has had a nasty bug that would make `sherpa-samp` quit when receiving a `stop` message from SAMP since the very first release. This is described in #11.
This PR fixes #11.
This PR also add error handling for fits performed when model expression is invalid, rather than relying on `sherpa-samp's` error handling.

Fitting tool RFEs

---

iris-common/src/main/java/cfa/vo/iris/fitting/FitConfiguration.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FitController.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FittingMainView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/StilPlotter.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/SedModel.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/VisualizerComponentPreferences.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/VisualizerDataModel.java
iris-visualizer/src/test/java/cfa/vo/iris/fitting/FitControllerTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/plotter/StilPlotterTest.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/preferences/SedPreferencesTest.java
iris/src/test/java/cfa/vo/iris/fitting/IrisFunctionalIT.java

Includes changes for:
+ Making model evaluation synchronous, and show the exception if the re-evaluation fails.
+ Adjusting the hashCode method in the FitConfiguration class. Save the hashCode when performing a fit.
+ Showing a warning window before saving if the FitConfiguration has changed since the last fit.
Right now there's no warning window for when users are just changing param values, that's WIP, but I'm switching gears to get the async serialization stuff in today.

Fitting warnings and error handling

---

sed-builder/src/main/java/cfa/vo/sed/science/stacker/SedStackerFrame.form
sed-builder/src/main/java/cfa/vo/sed/science/stacker/SedStackerFrame.java
sed-builder/src/main/java/cfa/vo/sed/science/stacker/SedStackerStacker.java

This PR addresses the following sedstacker-related bugs and RFE's:
- Segment name on Plotter legend is a messy UID of that segment layer. Now, the segment Target name of the stacked segment is set to the name of the Stack.
- Typo fixes on sedstacker GUI (#98).
- Add a "Remove" option when the user right-clicks on a Stack in the "Open Stacks" list (#99).

Miscellaneous sedstacker bug fixes and RFE's

---

sed-builder/src/main/java/cfa/vo/sed/science/stacker/SedStackerFrame.form
sed-builder/src/main/java/cfa/vo/sed/science/stacker/SedStackerFrame.java

This PR addresses #97 (sedstacker GUI: update layout).
Following suggestions from users after the Iris 2.1 release, the sedstacker frame is laid out in a horizontal fashion, so users will move from left to right on the frame as they work on a Stack. 
Open Stacks and Stack Management are on the left; a list of added SEDs (with Add/Remove capabilities) is in the center; redshifting, normalizing, and stacking options are on the far right.
I've tested the following buttons/options by hand:
- adding SEDs
- changing Stack names
- creating SEDs from the Stack
- deleting a Stack
- resetting a Stack
- switching between Stacks and making sure the configurations (redshifting, normalizing, stacking) update with the currently selected Stack
- "At point" and "By integration" normalization methods
- …

New sedstacker gui

---

iris-visualizer/src/test/java/cfa/vo/iris/visualizer/FittingToolComponentTest.java
iris/src/test/java/cfa/vo/iris/fitting/IrisFunctionalIT.java
pom.xml

There is a test consistently failing on travis with jdk8, but the test is OK when run (automatically or manually) on our development systems. We are ignoring the test for the time being.
This PR also removes an unnecessary loop waiting for menu to be ready, since that happens in other parts of the functional test now.
I am disabling the retry functionality, as it only takes longer for tests to fail. However, I increased the timeout for a test that was failing.
Unfortunately, there are still erratic failures, but the tests seem to pass more than 50% of the time now.

Make travis ci tests more likely to pass

---

iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/StilPlotter.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/plotter/StilPlotterTest.java

This PR addresses bug #332. 
When switching from a linear scale to a logarithmic scale on a fixed plot, the X and Y axis ranges are checked for negative values. If no negative axes ranges are found, the aspect is kept and used for the updated display. Otherwise, the display is reset to the full, default view of the SED. In other words, if _either axis_ has a minimum value of 0 or less, the whole plot is reset, even if the offending axis is to remain linear.
The check is done in StilPlotter.resetPlot().
A test which follows the steps reported in the #332 bug report is added to StilPlotterTest. Tests were also done by hand to check the code works as expected with various plot scale changes.

Fixes issue 332 (plotting negative values on a fixed log plot)

---

iris-common/src/main/java/cfa/vo/iris/fitting/FitConfiguration.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FitController.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FittingMainView.form
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FittingMainView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/StilPlotter.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/SedModel.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/plotter/StilPlotterTest.java
iris/src/main/java/cfa/vo/iris/vizier/VizierFrame.java

Addresses:
#336 
ChandraCXC/iris-dev/issues/118
These changes are minor updates to the Fitting Tool:
- (ChandraCXC/iris-dev/issues/118) The "Add Ranges" button is moved to be above the "Fit" button and associated widgets.
- (#336) When a SED is fit, its model is cleared, and then changed (new segment, new masked points), a "SED changed" warning no longer appears. 
The warning is called from `StilPlotter.validateModelFunctions()` if `SedModel.hasModelFunction` is True or if the SedModel's model version has changed. This PR sets `hasModelFunction` to False in `SedModel.clearFittingData()`.
A test has been added to StilPlotter.testModelFunctionValidity() to check the fix to #336. Testing was done by hand to check that masking or otherwise editing the SED after the model was cleared did not …

Move "Add ranges" button and prevent unnecessary 'SED changed' warning

---

iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/LayerModel.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/VisualizerDataModel.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/plotter/StilPlotterTest.java

Addresses #334 - "_ERROR" is appended to each Segment label in the Plotter legend
This change fixes #334 by setting the LayerModel's `leglabel` in VisualizerDataModel to the LayerModel's `suffix` (which by default is the segment StarTable's name). Like the metadata browser, the legend labels are incremented by 1, 2, 3, etc. for segments which share the same base table name. 
For example, if there are two segments with the target name "MESSIER 87", the first segment plotted has the label "MESSIER 87," while the second one is labeled "MESSIER 87 1". A third segment of the same name would be "MESSIER 87 2".
Before this fix, the LayerModel's `leglabel` property was always set to 'null'. By default, STILTS uses the `suffix` property as the Layer's label if the `leglabel` property isn't set. …

Bug 334 error in legend label

---

.gitignore
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FittingMainView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.form
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/plotter/PlotterView.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/FittingToolComponentTest.java
iris/src/test/java/cfa/vo/iris/fitting/IrisFunctionalIT.java

This PR fixed ChandraCXC/iris-dev#89, where no warning message appeared if the user tries to overwrite an existing file. Now a warning message pops up asking the user if they wish to overwrite the file or not.
Also added to this PR is the removal of the 'Flux/Flux Density' spinner from the Plot window, as it is unused.
The `.gitignore` file is updated to exlcude *.DS_store files.
Tests for overwriting and canceling the overwrite have been added to the functions `testSaveText()` and `testSaveJson()` in FittingToolComponentTest.java. Tests were also performed by hand to ensure the right confirmation message appeared when selecting an existing filename in the JFileChooser, and that all the buttons -- Yes, No, and the dispose 'X' button -- worked as expected.

Iris dev #89 no warning save model

---

iris-common/src/main/java/cfa/vo/iris/gui/widgets/ModelParameterPanel.java
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FittingMainView.java
iris/src/test/java/cfa/vo/iris/fitting/IrisFunctionalIT.java

This PR ensures that when clicking "Clear All" in the fitting tool, if a parameter is selected in the model view panel, then the parameter is cleared as well.

Make sure clearAll button clears selected parameter, if any

---

iris-visualizer/src/main/java/cfa/vo/iris/visualizer/metadata/MetadataBrowserMainView.java
iris-visualizer/src/main/java/cfa/vo/iris/visualizer/preferences/VisualizerComponentPreferences.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/metadata/MetadataBrowserMainViewTest.java

I can't reproduce ChandraCXC/iris-dev#128. However, investigating the issue I found out the implementation of the extraction could be made safer and asynchronous. At the very least, if the issue can be reproduced on some systems, this PR should minimize it by a) not stopping the GUI thread and b) by creating and populating the SED first and adding it to the SedManager only when ready.
A couple of questions for @jbudynk on the UI. I didn't include a spinning wheel, do you think we need one? Also, I did not add a Stop button as the Stop functionality should be implemented, and I didn't look into what that would require. If you feel strongly we should add a Stop button I'll look into it, maybe after we have addressed the current outstanding issues.

make sed extraction asynchronous and safer

---

iris-visualizer/src/main/java/cfa/vo/iris/visualizer/metadata/IrisStarJTable.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/metadata/IrisStarJTableTest.java

This PR fixes ChandraCXC/iris-dev#116 by properly handling the index column.
There is an issue, though it pre-exists this PR: [this test](https://github.com/ChandraCXC/iris/blob/081f1a86078362748af0bacc2af985c3bffe73ff/iris-visualizer/src/test/java/cfa/vo/iris/visualizer/metadata/IrisStarJTableTest.java#L255) seems to suggest sorting order should be preserved when a segment is added to an SED. However, that does not seem the case when running Iris. This PR does not fix that issue, but the fix will hopefully be compatible with an actual fix.

Handle index column sorting (and fix ChandraCXC/iris-dev#116)

---

iris-visualizer/src/main/java/cfa/vo/iris/fitting/FittingMainView.form
iris-visualizer/src/main/java/cfa/vo/iris/fitting/FittingMainView.java
iris-visualizer/src/test/java/cfa/vo/iris/visualizer/FittingToolComponentTest.java
iris/src/test/java/cfa/vo/iris/fitting/IrisFunctionalIT.java

This PR makes sure that the fit summary panel is updated when a SED is selected, not only after a fit.
A test was failing on Travis, so I added another timeout.
This PR also reverts back most of the changes in PR #340 that introduced issues in the Fitting Tool GUI

Fix irisdev 131 update fit stats

---

iris-common/src/main/java/cfa/vo/sherpa/SherpaClient.java
iris/distro/Iris

Similarly to #352, this makes sure confidence calculations graciously time out.

increase timeout and avoid retry when computing confidence

---

iris-common/pom.xml
iris-visualizer/pom.xml
samp-factory/pom.xml
sed-builder/pom.xml
test-components/pom.xml

This PR addresses #153: Update documentation for Iris 3.0.
The user documentation in iris-docs has major changes for the v3.0 updates, mainly for the visualizer and fitting tool. See ChandraCXC/iris-docs#1 for more details.
This PR also fixes broken and missing links to the maven Project Information, specifically for the iris-asdc-plugin and iris-test-data. All child module POM's now include descriptions for each module. These appear on the "Project Information --> Modules" page.

Update docs for Iris 3.0
